kiss-vm: add --bootc option, not finish yet
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -2141,6 +2141,8 @@ Usage() {
 	                 #will auto search url according distro name, if url omitted
 	  -C, -F, --usb-cd <iso/image path>
 	                 #create VM by using ISO or image file
+	  --bootc <to=|cmdlurl=>
+	                 #don't use, not finished yet
 	  --ks <file>    #kickstart file, will auto generate according distro name if omitting
 	  --ks-append <kickstart file fragment>
 	                 #append to default kickstart file that auto generated by kiss-vm
@@ -2493,6 +2495,7 @@ _at=`getopt -o hu:d:m:L::l:C:F:fn:gb:p:I::i:rvdx::Pqw:: \
 	--long user: \
 	--long enable-nested-kvm --long enable-nested-vm \
 	--long debug \
+	--long bootc: \
 	--long ks-fstype: \
 	--long ks: \
 	--long ks-pkgs: \
@@ -2626,6 +2629,7 @@ while true; do
 	--usb-cd)  InstallType=cdrom_image; Isourl=$2; CDROM_BUS_TYPE=usb; shift 2;;
 	-L|-l)     InstallType=location; _url=${2#=}; read Location BOOT_DISK_ATTRS <<<"${_url/,/ }"; shift 2;;
 	-I|-i)     InstallType=import; _url=${2#=}; read Imageurl BOOT_DISK_ATTRS <<<"${_url/,/ }"; shift 2;;
+	--bootc)   bootc=yes; bootcArg=${2}; shift 2;;
 	-P|--pxe)  InstallType=pxe; shift 1;;
 	--to-disk) TO_DISK="$(readlink -f "$2")"; shift 2;;
 	--diskless) DISKLESS=yes; shift 1;;
@@ -3105,17 +3109,31 @@ shopt -s extglob
 decodeDistro() {
 	local d="$1"
 	if [[ "$Intranet" = yes ]]; then
-		case ${d%[rn]} in
-		(5) Distro=RHEL5-Server-U11;; (6) Distro=RHEL-6.10;;
-		(7) Distro="RHEL-7.9-updates-????????.[0-9]+";;
-		(7.+([0-9])) Distro="RHEL-${d}-updates-????????.[0-9]+";;
-		(8|9) Distro="rhel-${d%[rn]}.[0-9]+.[0-9]+-????????.[0-9]+";;
-		(1[0-9]) Distro="rhel-${d%[rn]}.[0-9]+-????????.[0-9]+";;
-		(@(8|9).+([0-9])) Distro="RHEL-${d}.[0-9]-updates-????????.[0-9]+";;
-		(@(1[0-9]).+([0-9])) Distro="RHEL-${d}-updates-????????.[0-9]+";;
-		(fedora) Distro="Fedora-[0-9]+";;
-		esac
-		[[ ${d} = *r ]] && case ${d%r} in (8|9|1[0-9]) Distro="rhel-${d%r}.[0-9]+.[0-9]+";; esac
+		if [[ "$bootc" == yes ]]; then
+			if [[ "$d" =~ ^[0-9.]+n?$ ]]; then
+				echo "{debug} expanding DISTRO pattern: $d (bootc mode) ..." >&2
+				bootcTo=$(skopeo list-tags --retry-times 16 docker://images.paas.redhat.com/bootc/rhel-bootc |
+					jq -r '.Tags[]' | grep RHEL-${d%n} | tail -1)
+				Distro=$(skopeo inspect --retry-times 16 docker://images.paas.redhat.com/bootc/rhel-bootc:$bootcTo |
+					jq -r '.Labels["redhat.compose-id"]')
+				if [[ -z "$Distro" ]]; then
+					echo "{warn} expanding DISTRO pattern: $d fail" >&2
+				fi
+			fi
+		else
+			echo "{debug} expanding DISTRO pattern: $d ..." >&2
+			case ${d%[rn]} in
+			(5) Distro=RHEL5-Server-U11;; (6) Distro=RHEL-6.10;;
+			(7) Distro="RHEL-7.9-updates-????????.[0-9]+";;
+			(7.+([0-9])) Distro="RHEL-${d}-updates-????????.[0-9]+";;
+			(8|9) Distro="rhel-${d%[rn]}.[0-9]+.[0-9]+-????????.[0-9]+";;
+			(1[0-9]) Distro="rhel-${d%[rn]}.[0-9]+-????????.[0-9]+";;
+			(@(8|9).+([0-9])) Distro="RHEL-${d}.[0-9]-updates-????????.[0-9]+";;
+			(@(1[0-9]).+([0-9])) Distro="RHEL-${d}-updates-????????.[0-9]+";;
+			(fedora) Distro="Fedora-[0-9]+";;
+			esac
+			[[ ${d} = *r ]] && case ${d%r} in (8|9|1[0-9]) Distro="rhel-${d%r}.[0-9]+.[0-9]+";; esac
+		fi
 	else
 		case ${d%[rn]} in
 		(6|7) Distro="CentOS-${d%[rn]}";;
