kiss-vm: warning and exit if user use macvltap over wifi/wireless
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -2507,21 +2507,19 @@ while true; do
 	--net)
 		read netname _arg <<<"${2/,/ }"
 		if [[ -n "$netname" && "$netname" != none ]]; then
-			NETWORK_OPTS+=" --network=network=$netname,$(_netarg $_arg)";
-		else
-			NETWORK_OPTS=" "
+			NETWORK_OPTS+=("--network=network=$netname,$(_netarg $_arg)");
 		fi
 		shift 2;;
 	--net-br)
 		read brname _arg <<<"${2/,/ }"
-		NETWORK_OPTS+=" --network=bridge=$brname,$(_netarg $_arg)"; shift 2;;
+		NETWORK_OPTS+=("--network=bridge=$brname,$(_netarg $_arg)"); shift 2;;
 	--net-macvtap|--netmacvtap)
 		read srcif _arg <<<"${2/,/ }"
 		[[ "$srcif" = - || "$srcif" = default ]] && srcif=
 		srcif=${srcif:-$(get_default_if)}
 		_arg=$(_netarg $_arg)
 		[[ "$_arg" != *source_mode=* ]] && _arg=source_mode=$MacvtapMode,$_arg
-		NETWORK_OPTS+=" --network=type=direct,source=$srcif,$_arg"; shift 2;;
+		NETWORK_OPTS+=("--network=type=direct,source=$srcif,$_arg"); shift 2;;
 	--macvtapmode)   MacvtapMode="$2"; shift 2;;
 	--saveimage|--sa)
 		SAVE_IMAGE="yes"
@@ -3362,10 +3360,21 @@ fi
 	echo -e 'y\n' | ssh-keygen -q -t ecdsa -f ~/.ssh/id_ecdsa -N ''
 }
 # prepare network option
-[[ -z "$NETWORK_OPTS" ]] && {
+if [[ "${#NETWORK_OPTS[@]}" -gt 0 ]]; then
+	for ((i=0; i < ${#NETWORK_OPTS[@]}; i++)); do
+		netopt=${NETWORK_OPTS[$i]}
+		sif=$(sed -rn '/.*\<source=([^,]+)(,.*|$)/{s//\1/;p}' <<<"${netopt}")
+		[[ -d /sys/class/net/$sif/wireless ]] && {
+			echo -e "{VM:ERROR} '$sif': macvlan/macvtap does not work on wireless interface" >&2
+			exit 0
+		}
+	done
+else
 	srcif=$(get_default_if)
+	defaultSecondNetOpt="--network=type=direct,source=$srcif,source_mode=$MacvtapMode"
+	[[ -d /sys/class/net/$srcif/wireless ]] && defaultSecondNetOpt="--network=network=kissnet"
 	if [[ "$InstallType" = pxe ]]; then
-		NETWORK_OPTS="--network=type=direct,source=$srcif,source_mode=$MacvtapMode,model=${DEFAULT_IF_MODEL}"
+		NETWORK_OPTS=("--network=type=direct,source=$srcif,source_mode=$MacvtapMode,model=${DEFAULT_IF_MODEL}")
 	elif [[ "$WIN_AUTO" = yes ]]; then
 		gen_virt_mac() { echo -n 54:52:00$(od -txC -An -N3 /dev/random | tr \  :); }
 		WIN_MAC_INT=$(gen_virt_mac); WIN_MAC_EXT=$(gen_virt_mac)
@@ -3375,11 +3384,11 @@ fi
 			case "$WIN_TEMPLATE" in (base) WIN_IF_MODEL=virtio;; esac
 			intIfModel=e1000
 		fi
-		NETWORK_OPTS="--network=network=default,mac=$WIN_MAC_INT,model=${intIfModel} --network=type=direct,source=$srcif,source_mode=$MacvtapMode,mac=$WIN_MAC_EXT,model=${WIN_IF_MODEL}"
+		NETWORK_OPTS=("--network=network=default,mac=$WIN_MAC_INT,model=${intIfModel}" "$defaultSecondNetOpt,mac=$WIN_MAC_EXT,model=${WIN_IF_MODEL}")
 	else
-		NETWORK_OPTS="--network=network=default,model=${DEFAULT_IF_MODEL} --network=type=direct,source=$srcif,source_mode=$MacvtapMode,model=${DEFAULT_IF_MODEL}"
+		NETWORK_OPTS=("--network=network=default,model=${DEFAULT_IF_MODEL}" "${defaultSecondNetOpt},model=${DEFAULT_IF_MODEL}")
 	fi
-}
+fi
 
 ### hostdev option
 HOST_DEV_OPTS=()
@@ -3687,7 +3696,7 @@ if [[ "$InstallType" = location ]]; then
 	  ${ARCH_OPT} \
 	  $MEM_OPTS \
 	  $DISK_OPTS \
-	  $NETWORK_OPTS \
+	  "${NETWORK_OPTS[@]}" \
 	  $CONTROLLER_OPTS \
 	  "${HOST_DEV_OPTS[@]}" \
 	  --initrd-inject $KSPath \
@@ -3904,7 +3913,7 @@ elif [[ "$InstallType" = import ]]; then
 	  $MEM_OPTS \
 	  $DISK_OPTS \
 	  $CLOUD_INIT_OPT \
-	  $NETWORK_OPTS \
+	  "${NETWORK_OPTS[@]}" \
 	  $CONTROLLER_OPTS \
 	  "${HOST_DEV_OPTS[@]}" \
 	  $VTPM_OPT \
@@ -4161,7 +4170,7 @@ elif [[ "$InstallType" = pxe ]]; then
 	  --vcpus ${VCPUS} \
 	  ${ARCH_OPT} \
 	  $MEM_OPTS \
-	  ${NETWORK_OPTS} \
+	  "${NETWORK_OPTS[@]}" \
 	  "${HOST_DEV_OPTS[@]}" \
 	  $VTPM_OPT \
 	  ${VIDEO_OPT} \
@@ -4363,7 +4372,7 @@ elif [[ "$InstallType" = cdrom_image ]]; then
 	  ${ARCH_OPT} \
 	  $MEM_OPTS \
 	  $DISK_OPTS \
-	  $NETWORK_OPTS \
+	  "${NETWORK_OPTS[@]}" \
 	  $CONTROLLER_OPTS \
 	  "${HOST_DEV_OPTS[@]}" \
 	  $VTPM_OPT \
