kiss-vm: fix vncdo capture screen fail
virt-viewer does not share connect by default, add -s,--share opt

Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -353,9 +353,11 @@ vmifaddr() {
 }
 
 vmviewer() {
-	echo "{VM:INFO} redirect to: virt-viewer ..."
+	echo "{VM:INFO} redirect to: virt-viewer -s ..."
 	local logf=$RuntimeTmp/vmviewer-$$.log
-	run -debug -nohup=$logf virt-viewer -v "$@"
+	local waitopt=
+	[[ "$WAIT" = yes ]] && waitopt=-w
+	run -debug -nohup=$logf virt-viewer -s -v $waitopt "$@"
 	sleep 1; cat $logf 2>/dev/null
 }
 
@@ -377,7 +379,8 @@ image_binarize() {
 	local srcf=${1}
 	local dstf=${2:-new-${srcf}}
 
-	if command -v anytopnm >/dev/null; then
+	GMFirst=${GMFirst:-no}
+	if [[ "$GMFirst" != yes ]] && command -v anytopnm >/dev/null; then
 		anytopnm $srcf | ppmtopgm | pgmtopbm -threshold | pnmtopng > $dstf
 	else
 		local ConvertCmd="gm convert"
@@ -407,7 +410,10 @@ vncget() {
 		return 1
 	}
 	vncdo -s $vncport capture $RuntimeTmp/_screen.png
-	image_binarize $RuntimeTmp/_screen.png $RuntimeTmp/_screen2.png || return 1
+	[[ ! -s $RuntimeTmp/_screen.png ]] && {
+		echo "{VM:WARN} vncdo capture fail, it might because that conflict with unshared 'virt-viewer'" >&2
+	}
+	image_binarize $RuntimeTmp/_screen.png $RuntimeTmp/_screen2.png
 	gocr -i $RuntimeTmp/_screen2.png 2>/dev/null | GREP_COLORS='ms=01;30;47' grep --color .
 }
 
@@ -3160,13 +3166,13 @@ elif [[ "$InstallType" = pxe ]]; then
 	fi
 
 	if [[ -n $DISPLAY ]]; then
-		run -debug virt-viewer -v $vmname |& tee $VMpath/virt-viewer.log
+		run -debug virt-viewer -s -v $vmname |& tee $VMpath/virt-viewer.log
 		if grep -iq "server closed the connection" $VMpath/virt-viewer.log; then
 			until port_available ${vmname} $(_vmvncport $vmname); do sleep 1; done
-			run -debug -nohup=/dev/null virt-viewer -v $vmname
+			run -debug -nohup=/dev/null virt-viewer -s -v $vmname
 			echo -e "\n{VM:INFO} guest $vmname install finished"
 		else
-			echo -e "\n{VM:INFO} virt-viewer disconnected, run: 'virt-viewer $vmname' to finish install"
+			echo -e "\n{VM:INFO} virt-viewer disconnected, run: 'virt-viewer -s $vmname' to finish install"
 		fi
 	else
 		echo -e "\n{VM:INFO} please connect vnc to continue install:"
@@ -3350,12 +3356,12 @@ elif [[ "$InstallType" = cdrom ]]; then
 	fi
 
 	if [[ -n $DISPLAY ]]; then
-		run -debug virt-viewer -v $vmname |& tee $VMpath/virt-viewer.log
+		run -debug virt-viewer -s -v $vmname |& tee $VMpath/virt-viewer.log
 		if grep -iq "server closed the connection" $VMpath/virt-viewer.log; then
-			run -debug -nohup=/dev/null virt-viewer -v $vmname
+			run -debug -nohup=/dev/null virt-viewer -s -v $vmname
 			echo -e "\n{VM:INFO} guest $vmname install finished"
 		else
-			echo -e "\n{VM:INFO} virt-viewer exit, but seems install has not finished; you can run: 'virt-viewer $vmname' to finish install later"
+			echo -e "\n{VM:INFO} virt-viewer exit, but seems install has not finished; you can run: 'virt-viewer -s $vmname' to finish install later"
 		fi
 	else
 		echo -e "\n{VM:INFO} please connect vnc to continue install:"
