kiss-vm: fix code style about the snapshot patch
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -3100,69 +3100,69 @@ vm_snapshot(){
 
 	# Confirm that vm is there
 	if [[ -z "$vm_name" ]]; then
-		echo  "Error: missing VM name for snapshot operation"
+		echo "{VM:WARN} missing VM name for snapshot operation" >&2
 		return 1
 	fi
 
 	# Need to add a check that all the disks are qcow2 and sata 
 	case "$subcmd" in
-		create)
-			# Make sure the VM is shutdown before take snapshot
-			if virsh list --state-running --name | grep -q "^${vm_name}$"; then
-				read -p "VM $vm_name is running. Shutdown for consistent snapshot? (y/N) " -n 1 -r
-				echo
-				if [[ $REPLY =~ ^[Yy]$ ]]; then
-					echo "Shutting down VM $vm_name..."
-					virsh shutdown "$vm_name"
-					sleep 5
-					# If it still running then use destroy to force shutdown
-					if virsh list --state-running --name | grep -q "^${vm_name}$"; then
-						virsh destroy "$vm_name"
-					fi
+	create)
+		# Make sure the VM is shutdown before take snapshot
+		if virsh list --state-running --name | grep -q "^${vm_name}$"; then
+			read -p "VM $vm_name is running. Shutdown for consistent snapshot? (y/N) " -n 1 -r
+			echo
+			if [[ $REPLY =~ ^[Yy]$ ]]; then
+				echo "{VM:INFO} Shutting down VM $vm_name..."
+				virsh shutdown "$vm_name"
+				sleep 5
+				# If it still running then use destroy to force shutdown
+				if virsh list --state-running --name | grep -q "^${vm_name}$"; then
+					virsh destroy "$vm_name"
 				fi
 			fi
+		fi
 
-			echo "Creating snapshot '$snapshot_name' for VM '$vm_name'..."
-			#virsh snapshot-create-as "$vm_name" "$snapshot_name" --disk-only --atomic
-			virsh snapshot-create-as "$vm_name" "$snapshot_name"  --atomic
+		echo "{VM:INFO} Creating snapshot '$snapshot_name' for VM '$vm_name'..."
+		#virsh snapshot-create-as "$vm_name" "$snapshot_name" --disk-only --atomic
+		virsh snapshot-create-as "$vm_name" "$snapshot_name"  --atomic
 
-			virsh start $vm_name
-			vm_snapshot_ls $vm_name
-			;;
-		revert)
-			# Stop the VM before revert
-			if virsh list --state-running --name | grep -q "^${vm_name}$"; then
-				echo "Shutting down VM $vm_name to revert snapshot..."
-				virsh destroy "$vm_name"
-			fi
-			echo "Reverting VM '$vm_name' to snapshot '$snapshot_name'..."
-			virsh snapshot-revert "$vm_name" "$snapshot_name"
-
-			vm_snapshot_ls $vm_name
-			;;
-		ls)
-			vm_snapshot_ls $vm_name
-			;;
-		delete)
-			echo "Deleting snapshot '$snapshot_name' for VM '$vm_name'..."
-			virsh snapshot-delete "$vm_name" "$snapshot_name"
-
-			vm_snapshot_ls $vm_name
-			;;
-		*)
-			vm_snapshot_help
-			echo "Error: internal error - invalid snapshot subcommand '$subcmd'"
-			return 1
-			;;
+		virsh start $vm_name
+		vm_snapshot_ls $vm_name
+		;;
+	revert)
+		# Stop the VM before revert
+		if virsh list --state-running --name | grep -q "^${vm_name}$"; then
+			echo "{VM:INFO} Shutting down VM $vm_name to revert snapshot..."
+			virsh destroy "$vm_name"
+		fi
+		echo "{VM:INFO} Reverting VM '$vm_name' to snapshot '$snapshot_name'..."
+		virsh snapshot-revert "$vm_name" "$snapshot_name"
+		vm_snapshot_ls $vm_name
+		;;
+	ls)
+		vm_snapshot_ls $vm_name
+		;;
+	delete)
+		echo "{VM:INFO} Deleting snapshot '$snapshot_name' for VM '$vm_name'..."
+		virsh snapshot-delete "$vm_name" "$snapshot_name"
+		vm_snapshot_ls $vm_name
+		;;
+	help)
+		vm_snapshot_help
+		;;
+	help|*)
+		vm_snapshot_help
+		echo "{VM:ERROR} Invalid snapshot subcommand '$subcmd'" >&2
+		return 1
+		;;
 	esac
 
 	# Check the command result
 	local result=$?
 	if [[ $result -ne 0 ]]; then
-		echo "Error: snapshot operation '$subcmd' failed for VM '$vm_name'" >&2
+		echo "{VM:ERROR} snapshot operation '$subcmd' failed for VM '$vm_name'" >&2
 		return $result
 	fi
-
 }
 
 run -as=$VMUSER mkdir -p $RuntimeTmp ${DownloadImagePath}
