kiss-vm: exit if force remove vm fail
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -2401,7 +2401,9 @@ fi
 	virsh desc $vmname &>/dev/null && {
 		if [[ "${OVERWRITE}" = "yes" ]]; then
 			echo "{VM:INFO} VM $vmname has been there, remove it ..."
-			_vmdelete $vmname
+			_vmdelete $vmname || {
+				echo "{VM:ERR} delete $vmname fail, exit."
+			}
 		elif [[ "${DOWNLOAD_ONLY}" != "yes" ]]; then
 			echo "{VM:INFO} VM $vmname has been there, if you want overwrite please use --force option"
 			exit
