kiss-vm: verify distro name before search
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -930,6 +930,11 @@ is_intranet || {
 	exit 1
 }
 
+if egrep --color=always "[][~\!@#$^&()=,\":;{}|<>'\` ]" <<<"$Distro"; then
+	echo -e "{VM:WARN} ^^^ invalid character[s] in distro name: '$Distro'"
+	exit 1
+fi
+
 [[ "$Distro" = *[%*?]* ]] && {
 	dpattern=${Distro//./\\.}
 	dpattern=${dpattern//\?/.}
