kiss-vm: improve vm-exec, avoid: "Error opening terminal: unknown"
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -1296,14 +1296,14 @@ vmlogin() {
 		case $? in 0) sshstat=yes;; 1) sshstat=passwd;; esac
 		[[ "${EXEC}" = yes ]] && sshOpts+=" -n"
 		if [[ $sshstat = yes ]]; then
-			/usr/bin/ssh $sshOpts $U@$addr "${sshCommand}"
+			/usr/bin/ssh -tt $sshOpts $U@$addr "${sshCommand}"
 			rc=$?
 		elif [[ $sshstat = passwd ]]; then
 			expect <(cat <<-EOF
 			set timeout 120
 			set sshcmd [exec cat $RuntimeTmp/sshcmd]
 			log_user 0
-			spawn /usr/bin/ssh $sshOpts $U@$addr \$sshcmd
+			spawn /usr/bin/ssh -tt $sshOpts $U@$addr \$sshcmd
 			log_user 1
 			if {\$argc == 0 || \$sshcmd == ""} {
 				expect {
@@ -1328,10 +1328,10 @@ vmlogin() {
 			rc=$?
 		else
 			if [[ "${EXEC}" = yes ]]; then
-				echo -e "{VM:ERR} /usr/bin/ssh $sshOpts $U@$addr fail, exit." >&2
+				echo -e "{VM:ERR} /usr/bin/ssh -tt $sshOpts $U@$addr fail, exit." >&2
 				return 1
 			else
-				echo -e "{VM:WARN} /usr/bin/ssh $sshOpts $U@$addr fail, try login with console ..." >&2
+				echo -e "{VM:WARN} /usr/bin/ssh -tt $sshOpts $U@$addr fail, try login with console ..." >&2
 				virsh console "$_vmname"
 				rc=$?
 			fi
