kiss-vm: optimize code
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -1785,7 +1785,9 @@ Usage() {
 	                 #see also: virt-install --vcpus=?
 	                 #more info: https://www.quora.com/What-is-the-difference-between-CPU-core-die-and-package
 	  --arch         #Guest cpu arch. Note: require qemu-system-$arch already installed
-	  --qemucpu      #see also: `qemu-system-$arch -machine <$machine> -cpu help`
+	  --qemucpu <arg>
+	                 #alias of --qemu-opts="-cpu <arg>", and will cover it if both are specified
+	                 #see also: `qemu-system-$arch -machine <$machine> -cpu help`
 	  --nvmeboot,--NB #configure the boot disk as nvme device
 	                 #ref1: https://blog.christophersmart.com/2019/12/18/kvm-guests-with-emulated-ssd-and-nvme-drives/#comment-1060169
 	                 #ref2: https://www.qemu.org/docs/master/system/bootindex.html
@@ -2230,7 +2232,7 @@ while true; do
 	--msize)         MSIZE="$2"; shift 2;;
 	--cpus|--vcpus)  SPECIFIED_VCPUS=yes; VCPUS="$2"; shift 2;;
 	--arch)	         GuestARCH="$2"; ARCH_OPT=--arch=$GuestARCH; shift 2;;
-	--qemucpu)       QEMU_CPU=$2; QEMU_OPTS+=("--qemu-commandline=-cpu $2"); shift 2;;
+	--qemucpu)       QEMU_CPU=$2; QEMU_CPU_OPT="--qemu-commandline=-cpu $2"; shift 2;;
 	--nvmeboot|--NB) NVME_BOOT=yes; shift 1;;
 	--boot)          BOOT_OPTS+=("--boot=$2"); shift 2;;
 	--graphics)      GRAPHICS_OPT="--graphics=$2"; shift 2;;
@@ -2485,10 +2487,33 @@ else
 	esac
 fi
 
+if [[ -n "$QEMU_CPU_OPT" ]]; then
+	for ((i=0; i<${#QEMU_OPTS[@]}; i++)); do
+		if [[ "${QEMU_OPTS[$i]}" = *-cpu\ * ]]; then
+			QEMU_OPTS[$i]=$(echo "$QEMU_OPTS[$i]"|sed -r 's/-cpu [^,]+//')
+		fi
+	done
+	QEMU_OPTS+=("$QEMU_CPU_OPT")
+fi
+
 case "$GuestARCH" in
 (s390*) _MSIZE=2048;;
 esac
 
+fuzzy_match_cpu_model_name() {
+	local modelname=${1%%,*}
+	qemu-kvm -cpu ? | awk -v modelname=$modelname -v pat=".*${modelname,,}.*" '
+	{
+		if ($2 == modelname) {
+			yes++
+		} else if (tolower($2) ~ pat) {
+			if (length(m) == 0 || length(m) >= length($2)) { m=$2 }
+		}
+	}
+	END {
+		if (yes) { print modelname } else { print m }
+	}'
+}
 support_nested_kvm() {
 	local rc=1
 	if [[ "$OSTYPE" = linux-gnu* && "$HostARCH" = "$GuestARCH" ]]; then
@@ -2502,57 +2527,77 @@ support_nested_kvm() {
 	return $rc
 }
 support_nested_kvm && ENABLE_L2VM=${ENABLE_L2VM:-yes}
-[[ "$ENABLE_L2VM" = yes ]] && {
+if [[ "$ENABLE_L2VM" = yes ]]; then
 	kmodule=$(lsmod|awk '$1 == "kvm" {print $NF}')
 	cpuvendor=${kmodule#kvm_}
-	qemucpu=${QEMU_CPU:-host}
-	for qemuopt in "${QEMU_OPTS[@]}"; do
-		[[ "${qemuopt}" = *-cpu\ * ]] && IFS=, read qemucpu _ <<<"${qemuopt/*[= ]-cpu /}"
-	done
-	if [[ "$qemucpu" != host ]]; then
-		#fuzzy match
-		oqemucpu=$qemucpu
-		qemucpu=$(qemu-kvm -cpu ?| awk -v modelname=$qemucpu -v pat=".*${qemucpu,,}.*" '{
-			if ($2 == modelname) {
-				yes++
-			} else if (tolower($2) ~ pat) {
-				if (length(m) == 0 || length(m) >= length($2)) { m=$2 }
-			} }
-			END {
-				if (yes) { print modelname } else { print m }
-			}')
-		if [[ -z "$qemucpu" ]]; then
-			echo "{VM:ERROR}: can not find cpu model name '$oqemucpu', please check: qemu-kvm -cpu ?" >&2
+	modelname=host
+
+	alreadyHaveCpuOption=no
+	if [[ "${QEMU_OPTS[*]}" = *-cpu\ * ]]; then
+		alreadyHaveCpuOption=yes
+		for qemuopt in "${QEMU_OPTS[@]}"; do
+			[[ "${qemuopt}" = *-cpu\ * ]] && IFS=, read omodelname _ <<<"${qemuopt/*[= ]-cpu /}"
+		done
+		modelname=${omodelname}
+	fi
+
+	#if guest/qemu cpu is not host, fix cpuvendor
+	if [[ "$modelname" != host ]]; then
+		#verify cpu model name. fuzzy match
+		modelname=$(fuzzy_match_cpu_model_name $modelname)
+		if [[ -z "$modelname" ]]; then
+			echo "{VM:ERROR}: can not find cpu model name '$omodelname', please check: qemu-kvm -cpu ?" >&2
 			exit 2
 		fi
-		if $QEMU_KVM -cpu help|grep "$qemucpu .*alias of"; then
-			qemucpu=$($QEMU_KVM -cpu help|sed -rn "/$qemucpu/"'{s/.*alias of (.+)\).*/\1/;p}')
+
+		if $QEMU_KVM -cpu help|grep "$modelname .*alias of"; then
+			modelname=$($QEMU_KVM -cpu help|sed -rn "/$modelname/"'{s/.*alias of (.+)\).*/\1/;p}')
 		fi
-		_cpulist=$($QEMU_KVM -cpu help|sed -n "/$qemucpu/{s/)$//; p}")
+		_cpulist=$($QEMU_KVM -cpu help|sed -n "/$modelname/{s/)$//; p}")
 		if echo "$_cpulist"|grep -qw Intel; then
 			cpuvendor=intel
 		elif echo "$_cpulist"|grep -qw AMD; then
 			cpuvendor=amd
 		fi
 	fi
+
 	case $cpuvendor in
-	intel) flag=+vmx; cpuParam="$qemucpu,$flag";;
-	amd)   flag=+svm; cpuParam="$qemucpu,$flag";;
-	*)     flag=+fixme; cpuParam="$qemucpu,$flag";;
+	intel) flag=+vmx;;
+	amd)   flag=+svm;;
+	*)     flag=+fixme;;
 	esac
 
-	alreadyHaveCpuOption=no
+	if [[ $alreadyHaveCpuOption = yes ]]; then
+		for ((i=0; i<${#QEMU_OPTS[@]}; i++)); do
+			qemuopt="${QEMU_OPTS[$i]}"
+			if [[ "${qemuopt}" = *-cpu\ * ]]; then
+				QEMU_OPTS[$i]+=,${flag}
+				[[ "$omodelname" != "$modelname" ]] &&
+					QEMU_OPTS[$i]=$(echo "$QEMU_OPTS[$i]"|sed -r "s/-cpu [^,]+/-cpu $modelname/")
+				echo "${QEMU_OPTS[$i]/*[= ]-cpu /}"|awk '{print $1}'
+				break
+			fi
+		done
+	else
+		QEMU_OPTS+=("--qemu-commandline=-cpu $modelname,$flag")
+	fi
+else
 	for ((i=0; i<${#QEMU_OPTS[@]}; i++)); do
-		if [[ "${QEMU_OPTS[$i]}" = *-cpu\ * ]]; then
-			QEMU_OPTS[$i]+=,${flag}
-			QEMU_OPTS[$i]=$(echo "$QEMU_OPTS[$i]"|sed -r "s/-cpu [^,]+/-cpu $qemucpu/")
-			alreadyHaveCpuOption=yes
+		qemuopt="${QEMU_OPTS[$i]}"
+		if [[ "${qemuopt}" = *-cpu\ * ]]; then
+			IFS=, read omodelname _ <<<"${qemuopt/*[= ]-cpu /}"
+			modelname=$(fuzzy_match_cpu_model_name $omodelname)
+			if [[ -z "$modelname" ]]; then
+				echo "{VM:ERROR}: can not find cpu model name '$omodelname', please check: qemu-kvm -cpu ?" >&2
+				exit 2
+			fi
+			[[ "$omodelname" != "$modelname" ]] &&
+				QEMU_OPTS[$i]=$(echo "$QEMU_OPTS[$i]"|sed -r "s/-cpu [^,]+/-cpu $modelname/")
 			echo "${QEMU_OPTS[$i]/*[= ]-cpu /}"|awk '{print $1}'
 			break
 		fi
 	done
-	[[ $alreadyHaveCpuOption != yes ]] && QEMU_OPTS+=("--qemu-commandline=-cpu $cpuParam")
-}
+fi
 
 VCPUN=$(vcpuN "$VCPUS")
 
