kiss-*: add -x option for exec sub-command
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-netns b/kiss-netns
--- a/kiss-netns
+++ b/kiss-netns
@@ -67,33 +67,36 @@ Usage() {
 	  -h, --help           ; show this help info
 	  -v                   ; verbose mode
 	  -n <arg>             ; netns name
+	  -x [arg]             ; expected return code of sub-command exec, if doesn't match output test fail msg
+	                       ; e.g: -x 0  or  -x 1,2,3  or  -x 1,10,100-200
 
 	Examples: host connect ns0 with both veth and macvlan
 	  $P host,ve0.a-host,192.168.0.1---ns0,ve0.b-ns0,192.168.0.2  host,mv-host0,192.168.100.1 ns0,mv-ns0,192.168.100.2
-	  $P -v exec ns0 -- ping -c 2 192.168.0.1
-	  $P -v exec ns0 -- ping -c 2 192.168.100.1
+	  $P -vx exec ns0 -- ping -c 2 192.168.0.1
+	  $P -vx exec ns0 -- ping -c 2 192.168.100.1
 	  #curl -s -L https://raw.githubusercontent.com/tcler/linux-network-filesystems/master/tools/configure-nfs-server.sh | sudo bash
 	  sudo systemctl start nfs-server
 	  sudo exportfs -o ro,no_root_squash "*:/usr/share"
-	  $P -v exec ns0 -- showmount -e 192.168.0.1
-	  $P -v exec ns0 -- mkdir -p /mnt/ns0/nfs
-	  $P -v exec ns0 -- mount 192.168.0.1:/ /mnt/ns0/nfs
-	  $P -v exec ns0 -- mount -t nfs4
-	  $P -v exec ns0 -- ls /mnt/ns0/nfs/*
-	  $P -v exec ns0 -- umount /mnt/ns0/nfs
-	  $P -v exec ns0 -- rm -rf /mnt/ns0
+	  $P -vx exec ns0 -- showmount -e 192.168.0.1
+	  $P -vx exec ns0 -- mkdir -p /mnt/ns0/nfs
+	  $P -vx exec ns0 -- mount 192.168.0.1:/ /mnt/ns0/nfs
+	  $P -vx exec ns0 -- mount -t nfs4
+	  $P -vx exec ns0 -- ls /mnt/ns0/nfs
+	  $P -vx exec ns0 -- umount /mnt/ns0/nfs
+	  $P -vx exec ns0 -- umount /mnt/ns0/nfs
+	  $P -vx exec ns0 -- rm -rf /mnt/ns0
 	  $P del ns0
 	  $P delif mv-host0
 
 	Examples: host connect ns0 with both veth and ipvlan
 	  $P host,ve0.a-host,192.168.0.1---ns0,ve0.b-ns0,192.168.0.2   host,iv-host0,192.168.99.1 ns0,iv-ns0,192.168.99.2
-	  $P -v exec ns0 -- ping -c 2 192.168.99.1
+	  $P -vx exec ns0 -- ping -c 2 192.168.99.1
 	  $P del ns0
 	  $P delif iv-host0
 
 	Examples: host connect ns0 with veth and bridge br-0
 	  $P host,veth0.X,192.168.66.1---br-0,veth0.Y  br-0,veth1.Y---ns0,veth1.X,192.168.66.2
-	  $P -v exec ns0 -- ping -c 2 192.168.66.1
+	  $P -vx exec ns0 -- ping -c 2 192.168.66.1
 	  $P del ns0 br-0
 
 	EOF
@@ -134,6 +137,28 @@ netnsexec() {
 	local initpid=$(netns_init_pid $ns)
 	[[ "$nsverbose" = yes ]] && echo "- [NETNS:$ns] # $@" | GREP_COLORS='ms=01;36' grep --color . >&2
 	_netnsexec "$initpid" "$@"
+	rc=$?
+
+	[[ -n "$expectedrc" ]] && {
+		[[ " ${expectedrc[@]} " != *" $rc "* ]] && {
+			echo -e "\033[41m{TEST:FAIL} return code: expect $expectedRC, but got $rc\033[0m"
+		}
+	}
+
+	return $rc
+}
+
+expandrc() {
+	local rcrange=$1
+	local rclist=()
+	for rc in ${rcrange//,/ }; do
+		if [[ "$rc" =~ [0-9]+ ]]; then
+			rclist+=($rc)
+		elif [[ "$rc" =~ [0-9]+-[0-9]+ ]]; then
+			eval rclist+=({${rc/-/..}})
+		fi
+	done
+	echo -n ${rclist[@]}
 }
 
 netnsdelete() {
@@ -324,7 +349,7 @@ delif() {
 }
 
 # command line parse
-_at=`getopt -o hvn: \
+_at=`getopt -o hvn:x:: \
 	--long help \
     -a -n "$0" -- "$@"`
 eval set -- "$_at"
@@ -333,6 +358,7 @@ while true; do
 	-h|--help) Usage; shift 1; exit 0;;
 	-n) NS="$2"; shift 2;;
 	-v) nsverbose=yes; shift 1;;
+	-x) expectedRC=${2:-0}; expectedrc=$(expandrc $expectedRC); shift 2;;
 	--) shift; break;;
 	esac
 done
diff --git a/kiss-ns b/kiss-ns
--- a/kiss-ns
+++ b/kiss-ns
@@ -36,7 +36,8 @@ Usage() {
 	  --vol, --volatile {yes|no}  ; see systemd-nspawn --volatile. default is no
 	  --clone {ns}         ; clone from ns
 	  --noboot             ; no boot
-	  -x                   ; see systemd-nspawn -x, need btrfs as rootfs
+	  -x [arg]             ; expected return code of sub-command exec, if doesn't match output test fail msg
+	                       ; e.g: -x 0  or  -x 1,2,3  or  -x 1,10,100-200
 
 	Examples create ns by using mini fs tree + host /usr:
 	  # same as example ns1, but use a it's own fs tree instead reuse host os tree
@@ -57,19 +58,19 @@ Usage() {
 	  $P delete ns3                        # delete/remove ns3 and it's rootdir
 	  $P install ns2 cifs-utils            # install cifs-utils in ns2
 
-	  $P exec ns2 ip addr show             # exec command in ns2
-	  $P exec ns2 -- ls -l /               # exec command in ns2
+	  $P exec -vx ns2 ip addr show             # exec command in ns2
+	  $P exec -vx ns2 -- ls -l /               # exec command in ns2
 
 	  sudo systemctl start nfs-server
 	  sudo exportfs -o ro,no_root_squash "*:/usr/share"
 	  sudo addmacvlan macvlan-host
 	  sudo addressup macvlan-host 192.168.254.254
 	  sudo firewall-cmd --add-service=nfs --add-service=mountd --add-service=rpc-bind
-	  $P exec ns2 -- mkdir -p /mnt/nfs              # exec command in ns2
-	  $P exec ns2 -- showmount -e 192.168.2.1       # exec command in ns2
-	  $P exec ns2 -- mount 192.168.2.1:/ /mnt/nfs   # exec command in ns2
-	  $P exec ns2 -- showmount -e 192.168.254.254     # exec command in ns2
-	  $P exec ns2 -- mount 192.168.254.254:/ /mnt/nfs # exec command in ns2
+	  $P exec -vx ns2 -- mkdir -p /mnt/nfs              # exec command in ns2
+	  $P exec -vx ns2 -- showmount -e 192.168.2.1       # exec command in ns2
+	  $P exec -vx ns2 -- mount 192.168.2.1:/ /mnt/nfs   # exec command in ns2
+	  $P exec -vx ns2 -- showmount -e 192.168.254.254     # exec command in ns2
+	  $P exec -vx ns2 -- mount 192.168.254.254:/ /mnt/nfs # exec command in ns2
 
 	EOF
 }
@@ -182,6 +183,28 @@ nsexec() {
 	local initpid=$(ns_init_pid $ns)
 	[[ "$nsverbose" = yes ]] && echo "- [NS:$ns] # $@" | GREP_COLORS='ms=01;36' grep --color . >&2
 	_nsexec "$initpid" "$@"
+	rc=$?
+
+	[[ -n "$expectedrc" ]] && {
+		[[ " ${expectedrc[@]} " != *" $rc "* ]] && {
+			echo -e "\033[41m{TEST:FAIL} return code: expect $expectedRC, but got $rc\033[0m"
+		}
+	}
+
+	return $rc
+}
+
+expandrc() {
+	local rcrange=$1
+	local rclist=()
+	for rc in ${rcrange//,/ }; do
+		if [[ "$rc" =~ [0-9]+ ]]; then
+			rclist+=($rc)
+		elif [[ "$rc" =~ [0-9]+-[0-9]+ ]]; then
+			eval rclist+=({${rc/-/..}})
+		fi
+	done
+	echo -n ${rclist[@]}
 }
 
 getDefaultNic() {
@@ -238,7 +261,7 @@ InitPid=
 INIT_PKG=systemd
 
 # command line parse
-_at=`getopt -o hn:p:dxv \
+_at=`getopt -o hn:p:dvx:: \
 	--long help \
 	--long veth-ip: \
 	--long macvlan-ip: \
@@ -262,7 +285,7 @@ while true; do
 	--robind) BIND_OPTS+="--bind-ro=$2 "; shift 2;;
 	--volatile|--vol) VOLATILE_OPT="--volatile=$2"; shift 2;;
 	--clone) CLONE=$2; shift 2;;
-	-x) SHARE_SYSTEM=yes; shift 1;;
+	-x) expectedRC=${2:-0}; expectedrc=$(expandrc $expectedRC); shift 2;;
 	--noboot) BOOT_OPT=; INIT_PKG="bash"; shift 1;;
 	--) shift; break;;
 	esac
@@ -364,23 +387,19 @@ for addr in $NS_MACVLAN_IPS; do
 done
 
 mkdir -p $NSdir
-if [[ "$SHARE_SYSTEM" = yes ]]; then
-	MachineOpt="-x -D / -M $NS"
-else
-	echo -e "\n{NS:INFO} creating fs tree for NS $NSdir ..."
-	if [[ -n "$CLONE" && -d "$NSHome/$CLONE" ]]; then
-		rsync -a --info=progress2 $NSHome/$CLONE/  $NSdir/.
-		systemd-machine-id-setup --root $NSdir
-	fi
-	if rpm --root $NSdir -q $INIT_PKG; then
-		systemd-machine-id-setup --root $NSdir
-	else
-		chroot_install $NSdir $INIT_PKG $PKGS
-		\cp -rf /etc/yum.repos.d $NSdir/etc/.
-		\cp /etc/{passwd,group,shadow,resolv.conf} $NSdir/etc/.
-	fi
-	MachineOpt="-D $NSdir"
+echo -e "\n{NS:INFO} creating fs tree for NS $NSdir ..."
+if [[ -n "$CLONE" && -d "$NSHome/$CLONE" ]]; then
+	rsync -a --info=progress2 $NSHome/$CLONE/  $NSdir/.
+	systemd-machine-id-setup --root $NSdir
 fi
+if rpm --root $NSdir -q $INIT_PKG; then
+	systemd-machine-id-setup --root $NSdir
+else
+	chroot_install $NSdir $INIT_PKG $PKGS
+	\cp -rf /etc/yum.repos.d $NSdir/etc/.
+	\cp /etc/{passwd,group,shadow,resolv.conf} $NSdir/etc/.
+fi
+MachineOpt="-D $NSdir"
 
 NETWORK_VETH_OPT=
 [[ -n "$HOST_VETH_IP" && -n "$NS_VETH_IP" ]] && NETWORK_VETH_OPT=--network-veth
diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -336,9 +336,18 @@ vmlogin() {
 		exit \$value
 		EOF
 		) "$@"
-		return
+		rc=$?
+
+		[[ -n "$expectedrc" ]] && {
+			[[ " ${expectedrc[@]} " != *" $rc "* ]] && {
+				echo -e "\033[41m{TEST:FAIL} return code: expect $expectedRC, but got $rc\033[0m"
+			}
+		}
+
+		return $rc
 	done
 }
+
 vmexec() { EXEC=yes vmlogin "$@"; }
 vmlist() { virsh list --all; }
 netcreate() {
@@ -701,65 +710,67 @@ fi
 Usage() {
 	cat <<-'EOF'
 	Usage:
-	    vm [subcmd] <-d distroname> [OPTIONs] ...
+	  vm [subcmd] <-d distroname> [OPTIONs] ...
 
 	Options:
-	    -h, --help     #Display this help.
-	    --prepare      #check/install/configure libvirt and other dependent packages
-	    -I             #create VM by import existing disk image, auto search url according distro name
-	                    `-> just could be used in Intranet
-	    -i <url/path>  #create VM by import existing disk image, value can be url or local path
-	    -L             #create VM by using location, auto search url according distro name
-	                    `-> just could be used in Intranet
-	    -l <url>       #create VM by using location
-	    --ks <file>    #kickstart file, will auto generate according distro name if omitting
-	    -n|--vmname <name>
-	                   #VM name suffix, will auto generate according distro name if omitting
-	    --getvmname    #get *final* vmname. e.g:
-	                     vm -r --getvmname centos-8 -n nfsserv
-	                     vmname=$(vm -r --getvmname centos-8 -n nfsserv)
-	    -f|--force     #over write existing VM with same name
-	    -p|-pkginstall <pkgs>
-	                   #pkgs in default system repo, install by yum or apt-get
-	    -b|-brewinstall <args>
-	                   #pkgs in brew system or specified by url, install by internal brewinstall.sh
-	                    `-> just could be used in Intranet
-	    -g|-genimage   #generate VM image, after install shutdown VM and generate new qcow2.xz file
-	    --rm           #like --rm option of docker/podman, remove VM after quit from console
-	    --nocloud|--nocloud-init
-	                   #don't create cloud-init iso for the image that is not cloud image
-	    --osv <variant>
-	                   #OS_VARIANT, optional. virt-install will attempt to auto detect this value
-	                   # you can get [-osv variant] info by using:
-	                   $ osinfo-query os  #RHEL-7 and later
-	                   $ virt-install --os-variant list  #RHEL-6
-	    --nointeract   #exit from virsh console after install finish
-	    --saveimage [path]
-	                   #save image in path if install with import mode
-	    --cpus <N>     #number of virtual cpus, default 4
-	    --msize <size> #memory size, default 2048
-	    --dsize <size> #disk size, default 16
-	    --net <$name>  #join libvirt net $name
-	    --netmacvtap [source NIC]
-	                   #attach a macvtap interface
-	    --macvtapmode <vepa|bridge>
-	                   #macvtap mode
-	    -r|--ready     #virt config is ready, don't have to run enable_libvirt function
-	    --xdisk        #add 2 extra disk for test
-	    --nvdimm <nvdimm list> 
-	                   #one or more nvdimm specification, format: 511+1 (targetSize+labelSize)
-	                   #e.g: --nvdimm="511+1 1023+1" -> two nvdimm device
-	                   #e.g: --nvdimm="511 1023" -> two nvdimm device
-	                   #               ^^^^^^^^ default labelSize is 1, if omitting
-	                   #note: nvdimm function need qemu >= v2.6.0(RHEL/CentOS 8.0 or later)
-	    --nosshkey     #don't inject sshkey
-	    -v|--verbose   #verbose mode
-	    --xml          #just generate xml
-	    --qemu-opts    #Pass-through qemu options
-	    --qemu-env     #Pass-through qemu env[s]
-	    --enable-nested-vm  #enable nested on host
-	    --enable-guest-hypv #enable guest hypervisor, same as --qemu-opts="-cpu host,+vmx" or --qemu-opts="-cpu host,+svm"
-	                        #ref: https://www.linux-kvm.org/page/Nested_Guests
+	  -h, --help     #Display this help.
+	  --prepare      #check/install/configure libvirt and other dependent packages
+	  -I             #create VM by import existing disk image, auto search url according distro name
+	                  `-> just could be used in Intranet
+	  -i <url/path>  #create VM by import existing disk image, value can be url or local path
+	  -L             #create VM by using location, auto search url according distro name
+	                  `-> just could be used in Intranet
+	  -l <url>       #create VM by using location
+	  --ks <file>    #kickstart file, will auto generate according distro name if omitting
+	  -n|--vmname <name>
+	                 #VM name suffix, will auto generate according distro name if omitting
+	  --getvmname    #get *final* vmname. e.g:
+	                   vm -r --getvmname centos-8 -n nfsserv
+	                   vmname=$(vm -r --getvmname centos-8 -n nfsserv)
+	  -f|--force     #over write existing VM with same name
+	  -p|-pkginstall <pkgs>
+	                 #pkgs in default system repo, install by yum or apt-get
+	  -b|-brewinstall <args>
+	                 #pkgs in brew system or specified by url, install by internal brewinstall.sh
+	                  `-> just could be used in Intranet
+	  -g|-genimage   #generate VM image, after install shutdown VM and generate new qcow2.xz file
+	  --rm           #like --rm option of docker/podman, remove VM after quit from console
+	  --nocloud|--nocloud-init
+	                 #don't create cloud-init iso for the image that is not cloud image
+	  --osv <variant>
+	                 #OS_VARIANT, optional. virt-install will attempt to auto detect this value
+	                 # you can get [-osv variant] info by using:
+	                 $ osinfo-query os  #RHEL-7 and later
+	                 $ virt-install --os-variant list  #RHEL-6
+	  --nointeract   #exit from virsh console after install finish
+	  --saveimage [path]
+	                 #save image in path if install with import mode
+	  --cpus <N>     #number of virtual cpus, default 4
+	  --msize <size> #memory size, default 2048
+	  --dsize <size> #disk size, default 16
+	  --net <$name>  #join libvirt net $name
+	  --netmacvtap [source NIC]
+	                 #attach a macvtap interface
+	  --macvtapmode <vepa|bridge>
+	                 #macvtap mode
+	  -r|--ready     #virt config is ready, don't have to run enable_libvirt function
+	  --xdisk        #add 2 extra disk for test
+	  --nvdimm <nvdimm list> 
+	                 #one or more nvdimm specification, format: 511+1 (targetSize+labelSize)
+	                 #e.g: --nvdimm="511+1 1023+1" -> two nvdimm device
+	                 #e.g: --nvdimm="511 1023" -> two nvdimm device
+	                 #               ^^^^^^^^ default labelSize is 1, if omitting
+	                 #note: nvdimm function need qemu >= v2.6.0(RHEL/CentOS 8.0 or later)
+	  --nosshkey     #don't inject sshkey
+	  -v|--verbose   #verbose mode
+	  --xml          #just generate xml
+	  --qemu-opts    #Pass-through qemu options
+	  --qemu-env     #Pass-through qemu env[s]
+	  --enable-nested-vm  #enable nested on host
+	  --enable-guest-hypv #enable guest hypervisor, same as --qemu-opts="-cpu host,+vmx" or --qemu-opts="-cpu host,+svm"
+	                      #ref: https://www.linux-kvm.org/page/Nested_Guests
+	  -x [arg]            #expected return code of sub-command exec, if doesn't match output test fail msg
+	                      #e.g: -x 0  or  -x 1,2,3  or  -x 1,10,100-200
 
 	EOF
 	[[ "$Intranet" = yes ]] && cat <<-EOF
@@ -808,7 +819,7 @@ Usage() {
 	    vm ifaddr [VM]       #show ip address    //you can use i,if,if* instead ifaddr
 	    vm vncport [VM]      #show vnc host:port //you can use v,vnc instead vncport
 	    vm edit [VM]         #edit vm xml file   //you can use ed,ed* instead edit
-	    vm exec "\$VM" -- "cmd"  #login VM and exec cmd  //you can use e,ex,ex* instead exec
+	    vm exec [-vx] "\$VM" -- "cmd"  #login VM and exec cmd  //you can use e,ex,ex* instead exec
 	    vm reboot [/w] [VM]  #reboot VM          //option /w indicate wait until reboot complete(port 22 is available)
 	    vm stop [VM]         #stop/shutdonw VM   //nil
 	    vm start [VM]        #start VM           //nil
@@ -820,8 +831,21 @@ Usage() {
 	EOF
 }
 
+expandrc() {
+	local rcrange=$1
+	local rclist=()
+	for rc in ${rcrange//,/ }; do
+		if [[ "$rc" =~ [0-9]+ ]]; then
+			rclist+=($rc)
+		elif [[ "$rc" =~ [0-9]+-[0-9]+ ]]; then
+			eval rclist+=({${rc/-/..}})
+		fi
+	done
+	echo -n ${rclist[@]}
+}
+
 # command line parse
-_at=`getopt -o hd:Ll:fn:gb:p:Ii:rv \
+_at=`getopt -o hd:Ll:fn:gb:p:Ii:rvx:: \
 	--long help \
 	--long prepare \
 	--long ks: \
@@ -903,6 +927,7 @@ while true; do
 	--qemu-env)      QEMU_ENV+=("--qemu-commandline=env=$2"); shift 2;;
 	--enable-nested-vm) ENABLE_NESTED=yes; shift 1;;
 	--enable-guest-hy*) ENABLE_L2VM=yes; shift 1;;
+	-x) expectedRC=${2:-0}; expectedrc=$(expandrc $expectedRC); shift 2;;
 	--) shift; break;;
 	esac
 done
