kiss-vm: update cloud image name s/-${arch}/.${arch}/
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -4750,7 +4750,7 @@ if [[ "$GenerateImage" = yes ]]; then
 	read _type _dev _target image < <(_vmblklist $vmname '\.(qcow2|qcow|raw)')
 	imgfilename=${image##*/}
 	imgfilename=${imgfilename#${VMUSER}-}
-	[[ "$imgfilename" != *${GuestARCH}* ]] && imgfilename=$(echo $imgfilename|sed -r "s/\\.[^.]+$/-${GuestARCH}&/")
+	[[ "$imgfilename" != *${GuestARCH}* ]] && imgfilename=$(echo $imgfilename|sed -r "s/\\.[^.]+$/.${GuestARCH}&/")
 	newimage=$ImagePath/$Distro/${imgfilename}
 
 	echo -e "\n{VM:INFO} force shutdown $vmname ..."
@@ -4762,6 +4762,7 @@ if [[ "$GenerateImage" = yes ]]; then
 		cp ${image} ${newimage}
 	else
 		echo -e "\n{VM:INFO} virt-sparsify image $image to ${newimage} ..."
+		#LIBGUESTFS_BACKEND=direct virt-sparsify --check-tmpdir fail --tmp "$VMpath/tmp" ${image} ${newimage} || {
 		LIBGUESTFS_BACKEND=direct virt-sparsify --check-tmpdir fail ${image} ${newimage} || {
 			ls -lh ${image}
 			cp ${image} ${newimage}
