kiss-vm: add sub-command add.disk
Signed-off-by: Jianhong Yin <yin-jianhong@163.com>

diff --git a/kiss-vm b/kiss-vm
--- a/kiss-vm
+++ b/kiss-vm
@@ -947,13 +947,28 @@ vmadd_iso() {
 		echo -e "{VM:WARN} iso file '$isof' not exist ..."
 		return
 	fi
+
 	local xml=$(virsh dumpxml $vmname)
 	for _target in sd{c..z}; do echo "$xml"|grep -q -w $_target || break; done
-	virsh attach-disk $vmname $isof $_target --targetbus=sata --type cdrom --mode readonly
+	virsh attach-disk $vmname "$isof" $_target --targetbus=sata --type cdrom --mode readonly
 }
 
 vmadd_disk() {
-	:
+	local vmname=$1
+	local diskf=$2
+	local homedir=$(vm homedir $vmname |& head -1)
+	if [[ ! -d "$homedir" ]]; then
+		echo -e "{VM:ERROR} empty or invalide vm-homedir($homedir)"
+		return
+	fi
+	if [[ -f "$diskf" ]]; then
+		cp "$diskf" $homedir/.
+		diskf=$homedir/${diskf##*/}
+	fi
+
+	local xml=$(virsh dumpxml $vmname)
+	for _target in sd{a..z}; do echo "$xml"|grep -q -w $_target || break; done
+	virsh attach-disk $vmname "$diskf" $_target
 }
 
 vmadd_if() {
@@ -1842,6 +1857,7 @@ Usage() {
 	  $P cpfrom <VM> <file/dir_in_vm> <dst_dir/file_in_host>
 	  $P cpto   <VM> <files/dirs_in_host ...> <dst_dir_in_vm>
 	  $P add.iso <VM> <iso-file>
+	  $P add.disk <VM> <disk-file>
 	  $P add.if <VM> <network>
 	  $P add.if.direct <VM> <srcif>
 
